import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/Home.module.css";
import Footer from "../../components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Hello</h1>
        <Link href="/">Back to the Room</Link>
      </main>
      <Footer />
    </>
  );
}
