import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Canvas from "../components/Canvas";
import Footer from "../components/Footer";
import {
  html5,
  JavaScript,
  TypeScript,
  SaSS,
  Webpack,
  NodeJS,
  Css,
  python,
  Clang,
  TailwindCSS,
  vsCode,
  PostCSS,
  git,
} from "../utils/pathsSVG";
import {
  Events,
  Apps,
  Phone,
  Video,
  Webinars,
  TeamChat,
  MarketPlace,
  Solvvy,
  Whiteboard,
  Api,
  ZoomOI,
  DigitalSignage,
  ConferenceRooms,
  WorkSpace,
  ContactCenter,
} from "../utils/pathsSVG";
import { me, plant, belongings } from "../utils/pathsSVG";
export default function Home() {
  const dataSVGlang = [
    html5,
    SaSS,
    PostCSS,
    Clang,
    python,
    Css,
    TypeScript,
    JavaScript,
  ];
  const dataSVG = [Webpack, NodeJS, TailwindCSS, vsCode, git];
  const skillsSVG = [
    Events,
    Apps,
    Phone,
    Video,
    Webinars,
    TeamChat,
    MarketPlace,
    Solvvy,
    Whiteboard,
    Api,
    ZoomOI,
    DigitalSignage,
    ConferenceRooms,
    WorkSpace,
    ContactCenter,
  ];
  const roomSVG = [me, plant, belongings];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul className={styles.grid}>
          <li className={styles.card}>
            <Canvas
              width={500}
              height={500}
              className="sort"
              data={dataSVGlang}
            >
              <section className="myButtons">
                <button className="btn" type="button" data-sort="bubble">
                  BS
                </button>
                <button className="btn" type="button" data-sort="bubbleBack">
                  BSB
                </button>
                <button className="btn" type="button" data-sort="selection">
                  SS
                </button>
                <button className="btn" type="button" data-sort="selectionBack">
                  SSB
                </button>
                <button className="btn" type="button" data-sort="insertion">
                  IS
                </button>
              </section>
            </Canvas>
          </li>

          <li className={styles.card}>
            <Canvas width={500} height={500} className="room" data={roomSVG}>
              <section className="myButtons">
                <button className="btn" type="button" data-sort="bubble">
                  BS
                </button>
                <button className="btn" type="button" data-sort="bubbleBack">
                  BSB
                </button>
                <button className="btn" type="button" data-sort="selection">
                  SS
                </button>
                <button className="btn" type="button" data-sort="selectionBack">
                  SSB
                </button>
                <button className="btn" type="button" data-sort="insertion">
                  IS
                </button>
              </section>
            </Canvas>{" "}
          </li>

          <li className={styles.card}>
            <Canvas width={500} height={500} className="wheel" data={skillsSVG}>
              <section className="myButtons">
                <button className="btn" type="button" data-sort="bubble">
                  BS
                </button>
                <button className="btn" type="button" data-sort="bubbleBack">
                  BSB
                </button>
                <button className="btn" type="button" data-sort="selection">
                  SS
                </button>
                <button className="btn" type="button" data-sort="selectionBack">
                  SSB
                </button>
                <button className="btn" type="button" data-sort="insertion">
                  IS
                </button>
              </section>
            </Canvas>{" "}
          </li>
          <li className={styles.card}>
            <Canvas width={500} height={500} className="sort" data={dataSVG}>
              <section className="myButtons">
                <button className="btn" type="button" data-sort="bubble">
                  BS
                </button>
                <button className="btn" type="button" data-sort="bubbleBack">
                  BSB
                </button>
                <button className="btn" type="button" data-sort="selection">
                  SS
                </button>
                <button className="btn" type="button" data-sort="selectionBack">
                  SSB
                </button>
                <button className="btn" type="button" data-sort="insertion">
                  IS
                </button>
              </section>
              {/* <section className="myRange">
                <ul>
                  <li>
                    <label htmlFor="speed">Speed</label>
                    <br />
                    <input
                      type="range"
                      name="speed"
                      id="speed"
                      defaultValue="3"
                      min="1"
                      max="5"
                      // onChange={setSpeed()}
                    />
                  </li>
                  <li>
                    <label htmlFor="amount">Amount</label>
                    <br />
                    <input
                      type="range"
                      name="amount"
                      id="amount"
                      defaultValue="15"
                      min="3"
                      max="100"
                      // onChange="setAmount()"
                    />
                  </li>
                </ul>
              </section> */}
            </Canvas>
          </li>
        </ul>
      </main>
      <Footer />
    </>
  );
}
